### ISSUE TITLE
Not up to date with glitch site

### ISSUE THREAD

**Issue by hazycora** [samdutton/url-parts#2]
I was intending on making a PR (support for the public suffix list isn't quite right as it doesn't handle wildcards and excluded entries and the public suffix list data is outdated anyways), but I noticed the site wasn't working the same as it does on glitch (the URL I was checking included dashes and an error about only supporting ASCII was shown, the same error doesn't occur on glitch). I then realised the repository has much different code. Could this be updated?

**Comment by samdutton** [comment]
Oops — you're right. Thanks for the heads-up.

I've updated the repo now.

**Comment by hazycora** [comment]
Thank you! Sent the PR I was working on :)
